# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Lucy Baxandall
subtitle: Paperwoman
name: Lucy Baxandall
description: Lucy Baxandall art gallery
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "http://rare-dragonfly.cloudvent.net/"
#url: "https://www.lucybaxandall.com/"
logo: "/siteicon.png"
email: a.ward@eyedivision.com

# Build settings
markdown: kramdown
# paginate: 5
# paginate_path: "/page:num/"
# inter_post_navigation: false
permalink: pretty

# Image CDN
imagecdn:
  staging: "https://ed-lucybaxandall-dev.imgix.net"
  production: "https://ed-lucybaxandall.imgix.net"

# Collections
collections:
    work:
        output: true
        permalink: /work/:path/
        _hide_content: true
    products:
        output: true
        permalink: /products/:path/
        _hide_content: true

# Snipcart API key
snipcart_api_key: NzE2ODAzN2MtMWNkOS00NDNmLTlhNzYtYWI5Y2MwZGZhNDEyNjM2MTY3ODc5MzE4NzY1NjQz

# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "work"
        values:
            layout: "gallery"
    -
        scope:
            path: ""
            type: "shop"
        values:
            layout: "gallery"

# Google analytics
ga_tracking_id: "UA-72960331-1"

# Google Recaptcha for contact form
recaptcha_site_key: 6LdXwysUAAAAAAuPlVZIfOVpO9716wkvDHBHo2Wy

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: icon-twitter_sign
    username: LucyPaperBax
    url: https://twitter.com/LucyPaperBax
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: icon-facebook_sign
    username: lucybaxandallpaperwoman
    url: http://www.facebook.com/lucybaxandallpaperwoman
    desc: Like us on Facebook
    share: true


  - name: LinkedIn
    icon: linkedin
    username:
    url:
    desc: Connect with us on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: icon-instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url: http://uk.pinterest.com/lucybaxandall
    desc: Follow me on Pinterest
    share: true


  - name: Vimeo
    icon: vimeo-square
    username:
    url:
    desc: Follow me on Vimeo
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 480
    fb_image_height: 480
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

