# External gems - updated to plugins in jekyll v3.6
plugins:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
 # - jekyll-assets
 # - autoprefixer-rails
   - jekyll-seo-tag
   - jekyll-sitemap

# Site settings
title: Lucy Baxandall
subtitle: tidekettle paper
name: Lucy Baxandall
description: "Welcome to the world of handmade paper. You can find our papers here online and in our shop in Berwick-upon-Tweed. We also run regular hand papermaking workshops and classes around the country."
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "https://www.lucybaxandall.com"
#url: "https://www.lucybaxandall.com/"
logo: "/siteicon.png"
show_logo: false
email: "lucy.baxandall@morleycollege.ac.uk"
asset_url: "/assets/"

default_post_image: "/assets/images/road_closed.jpg"
default_gallery_image: "/assets/images/road_closed.jpg"

show_social_top: true
# Build settings
markdown: kramdown
# paginate: 5
# paginate_path: "/page:num/"
# inter_post_navigation: false
permalink: pretty
highlightjs_theme: "monokai-sublime"

# allow colcade / masonry layout
colcade: true

# Image CDN
imagecdn:
  staging: "https://ed-lucybaxandall-dev.imgix.net"
  production: "https://ed-lucybaxandall.imgix.net"

# Environment settings
appurl:
    development: "http://0.0.0.0:4000"
    staging: "https://rare-dragonfly.cloudvent.net"
    production: "https://www.lucybaxandall.com"

# Collections
collections:
    work:
        output: true
        permalink: /work/:path/
        _hide_content: true
    products:
        output: true
        permalink: /products/:path/
        _hide_content: true

# Snipcart API key
# snipcart_api_key: NzE2ODAzN2MtMWNkOS00NDNmLTlhNzYtYWI5Y2MwZGZhNDEyNjM2MTY3ODc5MzE4NzY1NjQz

# PayPal merchant ID
paypal_id: GHHS3LSA9994Y

# Default home page image
# bgimage: '/assets/header.jpg'

# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "work"
        values:
            layout: "gallery"
    -
        scope:
            path: ""
            type: "shop"
        values:
            layout: "gallery"

# Google analytics
ga_tracking_id: "UA-72960331-1"

# Google Recaptcha for contact form
recaptcha_site_key: "6LdXwysUAAAAAAuPlVZIfOVpO9716wkvDHBHo2Wy"

# https://docs.cloudcannon.com/editing/options/
_options:
  _text:            # text =
    link: true
    bold: true
    italic: true
    removeformat: true
  _block:           # block = editable blocks within pages
    link: true
    bold: true
    italic: true
    removeformat: true
    left: align-left
    center: center-this-text
    right: align-right
    justify: full-width-text
    undo: true
    redo: true
    format: p h2 h3 h4 h5 h6 div
    numberedlist: true
    bulletedlist: true
    blockquote: true
    image: true
    styles: /css/editor.scss
  content:
    link: true
    bold: true
    italic: true
    removeformat: true
    left: align-left
    center: center-this-text
    right: align-right
    justify: full-width-text
    undo: true
    redo: true
    format: p h2 h3 h4 h5 h6 div
    numberedlist: true
    bulletedlist: true
    blockquote: true
    image: true
    styles: /css/editor.scss

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: icon-twitter_sign
    username: LucyPaperBax
    url: https://twitter.com/LucyPaperBax
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: icon-facebook_sign
    username: lucybaxandallpaperwoman
    url: http://www.facebook.com/lucybaxandallpaperwoman
    desc: Like us on Facebook
    share: true

  - name: Pinterest
    icon: icon-pinterest
    username: lucybaxandall
    url: http://uk.pinterest.com/lucybaxandall
    desc: Follow me on Pinterest
    share: true

  - name: Instagram
    icon: icon-instagram
    username: lucypaperbax
    url: https://www.instagram.com/lucypaperbax/
    desc: Follow me on Instagram
    share: false


# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 480
    fb_image_height: 480
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

